from __future__ import annotations

import re
from typing import Any, TypedDict

from neurosight.governance.ai_safety import SafetyDecision, evaluate_ai_safety_prompt


def _extract_diagnosis_from_report(report_text: str) -> Any | None:
    """Extract diagnosis enum value from free-text report content.

    Args:
        report_text: Final or draft report text generated by the graph.

    Returns:
        The parsed Diagnosis enum when a supported diagnosis token is present,
        otherwise None.
    """
    from neurosight.contracts import Diagnosis

    normalized = report_text.lower()
    diagnosis_patterns: list[tuple[str, Any]] = [
        (r"\bfrontotemporal dementia\b", Diagnosis.FTD),
        (r"\bvascular dementia\b", Diagnosis.VD),
        (r"\blewy body dementia\b", Diagnosis.LBD),
        (r"\balzheimer(?:'s|s)?\b", Diagnosis.AD),
        (r"\bnormal\b", Diagnosis.NORMAL),
        (r"\bmci\b", Diagnosis.MCI),
        (r"\bad\b", Diagnosis.AD),
        (r"\bftd\b", Diagnosis.FTD),
        (r"\blbd\b", Diagnosis.LBD),
        (r"\bvd\b", Diagnosis.VD),
    ]

    for pattern, diagnosis in diagnosis_patterns:
        if re.search(pattern, normalized):
            return diagnosis
    return None


def _extract_confidence_from_report(report_text: str, requires_review: bool) -> float:
    """Estimate confidence from report text and review flag.

    Args:
        report_text: Final report text that may include confidence numbers.
        requires_review: Whether the workflow has already flagged human review.

    Returns:
        A normalized confidence score in the inclusive range [0.0, 1.0].
    """
    normalized = report_text.lower()
    candidates: list[float] = []

    for raw in re.findall(
        r"(?:confidence|prob(?:ability)?)\s*[:=]?\s*(\d+(?:\.\d+)?)\s*%?",
        normalized,
    ):
        value = float(raw)
        candidates.append(value / 100.0 if value > 1.0 else value)

    for raw in re.findall(r"(\d+(?:\.\d+)?)\s*%", normalized):
        candidates.append(float(raw) / 100.0)

    for raw in re.findall(r"\b(?:0(?:\.\d+)?|1(?:\.0+)?)\b", normalized):
        candidates.append(float(raw))

    if candidates:
        confidence = max(0.0, min(1.0, candidates[0]))
        if requires_review:
            return min(confidence, 0.74)
        return confidence

    return 0.4 if requires_review else 0.8


def _rule_based_safety_decision(query: str) -> SafetyDecision:
    """Apply deterministic AI safety rules for high-risk queries.

    Args:
        query: User question supplied to the diagnosis orchestrator.

    Returns:
        A structured safety decision describing guardrail outcome.
    """
    return evaluate_ai_safety_prompt(query)


def _rule_based_safety_block(query: str) -> tuple[bool, list[str]]:
    """Return the legacy block tuple for tests and older callers."""
    decision = _rule_based_safety_decision(query)
    return decision.action == "block", list(decision.flags)


class DiagnosisState(TypedDict):
    patient_id: str
    query: str
    patient_record: Any
    mri_findings: str
    eeg_findings: str
    cognitive_findings: str
    kg_context: str
    similar_patients: list[dict[str, Any]]
    draft_report: str
    final_report: str
    safety_verdict: str
    safety_flags: list[str]
    requires_review: bool
    next_agent: str
    messages: list[dict[str, Any]]
    iteration_count: int

MRI_ANALYST_PROMPT = "You are a neuroradiologist. Cite specific brain regions such as the hippocampus or medial temporal lobe."
EEG_ANALYST_PROMPT = "You are an EEG specialist. Cite specific frequency bands such as alpha slowing or theta excess."
COGNITIVE_ANALYST_PROMPT = "You are a neuropsychologist. Adjust cognitive scores for age and education level."
KG_RETRIEVER_PROMPT = "You retrieve temporal KG results to provide longitudinal clinical context."
REPORT_WRITER_PROMPT = "You format the final research evaluation report into 5 structured sections: Demographics, Simulated History, Modality Findings, Model-Generated Risk Profile, and Safety Disclaimers."
SAFETY_GUARDIAN_PROMPT = "You are an adversarial critic. BLOCK the output if: 1) Overconfident risk profile prediction (>0.95 on uncertain case). 2) Drug dosage mentioned without specialist review. 3) Missing emergency signs (stroke, tumor, bleed). 4) Critical differential not considered."

def build_diagnosis_graph(llm_client: Any = None, kg: Any = None) -> Any:
    try:
        from langgraph.graph import END, StateGraph
    except ImportError as exc:
        raise RuntimeError(
            "LangGraph is required to build the diagnosis graph. "
            "Install the pinned dependency `langgraph==0.1.1` from requirements.txt."
        ) from exc

    workflow = StateGraph(DiagnosisState)

    def supervisor_node(state: DiagnosisState) -> DiagnosisState:
        if state["iteration_count"] >= 10:
            raise RuntimeError("Circuit breaker")
        state["iteration_count"] += 1

        from neurosight.governance.safety_service import SafetyService
        query_text = str(state.get("query", ""))
        is_blocked, flags = SafetyService.evaluate_query_safety(query_text)
        if is_blocked:
            if state.get("final_report"):
                state["next_agent"] = END
            else:
                state["next_agent"] = "safety_guardian"
                state["safety_verdict"] = "block"
                state["safety_flags"] = flags
            return state

        pr = state.get("patient_record", {})

        if not state.get("mri_findings") and pr.get("mri"):
            state["next_agent"] = "mri_analyst"
        elif not state.get("eeg_findings") and pr.get("eeg"):
            state["next_agent"] = "eeg_analyst"
        elif not state.get("cognitive_findings") and pr.get("cognitive"):
            state["next_agent"] = "cognitive_analyst"
        elif not state.get("kg_context"):
            state["next_agent"] = "kg_retriever"
        elif not state.get("draft_report"):
            state["next_agent"] = "report_writer"
        elif not state.get("final_report"):
            state["next_agent"] = "safety_guardian"
        else:
            state["next_agent"] = END
        return state

    def mri_analyst_node(state: DiagnosisState) -> DiagnosisState:
        if llm_client is None:
            state["mri_findings"] = "LLM not configured — manual review required"
            return state
        try:
            from langchain_core.messages import HumanMessage, SystemMessage
            res = llm_client.invoke([SystemMessage(content=MRI_ANALYST_PROMPT), HumanMessage(content="Analyze MRI data.")])
            state["mri_findings"] = res.content
        except (AttributeError, ModuleNotFoundError, ImportError):
            state["mri_findings"] = "LLM not configured — manual review required"
        return state

    def eeg_analyst_node(state: DiagnosisState) -> DiagnosisState:
        if llm_client is None:
            state["eeg_findings"] = "LLM not configured — manual review required"
            return state
        try:
            from langchain_core.messages import HumanMessage, SystemMessage
            res = llm_client.invoke([SystemMessage(content=EEG_ANALYST_PROMPT), HumanMessage(content="Analyze EEG data.")])
            state["eeg_findings"] = res.content
        except (AttributeError, ModuleNotFoundError, ImportError):
            state["eeg_findings"] = "LLM not configured — manual review required"
        return state

    def cognitive_analyst_node(state: DiagnosisState) -> DiagnosisState:
        if llm_client is None:
            state["cognitive_findings"] = "LLM not configured — manual review required"
            return state
        try:
            from langchain_core.messages import HumanMessage, SystemMessage
            res = llm_client.invoke([SystemMessage(content=COGNITIVE_ANALYST_PROMPT), HumanMessage(content="Analyze cognitive data.")])
            state["cognitive_findings"] = res.content
        except (AttributeError, ModuleNotFoundError, ImportError):
            state["cognitive_findings"] = "LLM not configured — manual review required"
        return state

    def kg_retriever_node(state: DiagnosisState) -> DiagnosisState:
        if kg is None:
            state["kg_context"] = "No KG available"
            return state
        pid = state["patient_id"]
        hist = kg.get_patient_history(pid)
        sim = kg.find_similar_patients(pid)
        state["kg_context"] = f"History: {hist}, Similar: {sim}"
        return state

    def report_writer_node(state: DiagnosisState) -> DiagnosisState:
        if llm_client is None:
            state["draft_report"] = "LLM not configured — manual review required"
            return state
        try:
            from langchain_core.messages import HumanMessage, SystemMessage
            res = llm_client.invoke([SystemMessage(content=REPORT_WRITER_PROMPT), HumanMessage(content=f"Findings: {state}")])
            state["draft_report"] = res.content
        except (AttributeError, ModuleNotFoundError, ImportError):
            state["draft_report"] = "LLM not configured — manual review required"
        return state

    def safety_guardian_node(state: DiagnosisState) -> DiagnosisState:
        query_text = str(state.get("query", ""))
        safety_decision = _rule_based_safety_decision(query_text)
        safety_flags = list(safety_decision.flags)
        
        from neurosight.governance.safety_service import SafetyService
        is_service_blocked, service_flags = SafetyService.evaluate_query_safety(query_text)
        
        if is_service_blocked or state.get("safety_verdict") == "block" or safety_decision.action == "block":
            action = "block"
            safety_flags = list(set(safety_flags + service_flags + state.get("safety_flags", [])))
        elif safety_decision.action == "review":
            action = "review"
            safety_flags = list(set(safety_flags + service_flags + state.get("safety_flags", [])))
        else:
            action = "allow"
            
        state["safety_verdict"] = action
        if action == "block":
            state["final_report"] = (
                "BLOCKED: Deterministic AI safety policy triggered for a potentially "
                f"unsafe query. Flags={','.join(safety_flags)}. "
                f"OWASP={','.join(safety_decision.owasp_risks)}"
            )
            state["requires_review"] = True
            state["safety_flags"] = safety_flags
            return state
        if action == "review":
            state["requires_review"] = True
            state["safety_flags"] = safety_flags

        if llm_client is None:
            state["final_report"] = state.get("draft_report", "")
            if action == "review":
                state["final_report"] += (
                    "\nREVIEW: Deterministic AI safety policy requires human review. "
                    f"Flags={','.join(safety_flags)}"
                )
            else:
                state["safety_flags"] = []
            return state
        try:
            from langchain_core.messages import HumanMessage, SystemMessage
            res = llm_client.invoke([SystemMessage(content=SAFETY_GUARDIAN_PROMPT), HumanMessage(content=state.get("draft_report", ""))])
            content = res.content
            if "BLOCK" in content:
                state["final_report"] = "BLOCKED: " + content
                state["requires_review"] = True
                state["safety_flags"] = safety_flags + ["BLOCKED"]
            elif "REVIEW_NEEDED" in content:
                state["final_report"] = state.get("draft_report", "") + "\n⚠️ REVIEW: " + content
                state["requires_review"] = True
                state["safety_flags"] = safety_flags + ["REVIEW_NEEDED"]
            elif action == "review":
                state["final_report"] = (
                    state.get("draft_report", "")
                    + "\nREVIEW: Deterministic AI safety policy requires human review. "
                    + f"Flags={','.join(safety_flags)}"
                )
                state["requires_review"] = True
                state["safety_flags"] = safety_flags
            else:
                state["final_report"] = state.get("draft_report", "")
                state["safety_flags"] = []
        except (AttributeError, ModuleNotFoundError, ImportError):
            state["final_report"] = state.get("draft_report", "")
            if action == "review":
                state["final_report"] += (
                    "\nREVIEW: Deterministic AI safety policy requires human review. "
                    f"Flags={','.join(safety_flags)}"
                )
                state["requires_review"] = True
                state["safety_flags"] = safety_flags
            else:
                state["safety_flags"] = []
        return state

    workflow.add_node("supervisor", supervisor_node)
    workflow.add_node("mri_analyst", mri_analyst_node)
    workflow.add_node("eeg_analyst", eeg_analyst_node)
    workflow.add_node("cognitive_analyst", cognitive_analyst_node)
    workflow.add_node("kg_retriever", kg_retriever_node)
    workflow.add_node("report_writer", report_writer_node)
    workflow.add_node("safety_guardian", safety_guardian_node)

    workflow.set_entry_point("supervisor")

    workflow.add_conditional_edges("supervisor", lambda s: s["next_agent"], {
        "mri_analyst": "mri_analyst",
        "eeg_analyst": "eeg_analyst",
        "cognitive_analyst": "cognitive_analyst",
        "kg_retriever": "kg_retriever",
        "report_writer": "report_writer",
        "safety_guardian": "safety_guardian",
        END: END
    })

    workflow.add_edge("mri_analyst", "supervisor")
    workflow.add_edge("eeg_analyst", "supervisor")
    workflow.add_edge("cognitive_analyst", "supervisor")
    workflow.add_edge("kg_retriever", "supervisor")
    workflow.add_edge("report_writer", "supervisor")
    workflow.add_edge("safety_guardian", "supervisor")

    return workflow.compile()

def build_initial_state(patient_record: Any, query: Any) -> DiagnosisState:
    """Build the LangGraph input state for a patient/query pair."""
    return DiagnosisState(
        patient_id=patient_record.patient_id,
        query=query or "What is the model-generated risk profile?",
        patient_record=patient_record.__dict__ if hasattr(patient_record, "__dict__") else {},
        mri_findings=None,
        eeg_findings=None,
        cognitive_findings=None,
        kg_context="",
        similar_patients=[],
        draft_report="",
        final_report="",
        safety_verdict="",
        safety_flags=[],
        requires_review=False,
        next_agent="",
        messages=[],
        iteration_count=0,
    )


def build_report_from_state(result: dict[str, Any]) -> Any:
    """Convert a final LangGraph state into the public DiagnosisReport contract."""
    from neurosight.contracts import Diagnosis, DiagnosisReport
    from neurosight.governance.safety_service import SafetyService

    final_report = str(result.get("final_report", ""))
    blocked = "BLOCKED" in final_report.upper()
    requires_review = bool(result.get("requires_review", False)) or blocked

    parsed_diagnosis = _extract_diagnosis_from_report(final_report)
    if parsed_diagnosis is None:
        parsed_diagnosis = Diagnosis.MCI
        confidence = 0.0
        requires_review = True
    else:
        confidence = _extract_confidence_from_report(
            final_report,
            requires_review=requires_review,
        )

    # Format the report to ensure safety disclaimers and sanitization are applied
    formatted_report = SafetyService.format_report(final_report)

    return DiagnosisReport(
        patient_id=result["patient_id"],
        final_diagnosis=parsed_diagnosis,
        confidence=confidence,
        report_text=formatted_report,
        requires_review=requires_review,
        blocked_by_safety=blocked,
    )


def run_diagnosis(patient_record: Any, query: Any, graph: Any) -> Any:
    initial_state = build_initial_state(patient_record, query)
    result = graph.invoke(initial_state)
    return build_report_from_state(result)
